#系统端口
server:
  port: 8082
spring:
#数据库连接
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springBootTest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package:
  mapper-locations: classpath:mappers/*.xml

#log
logging:
  level:
    computer: info
  file:
    path: /Users/dengxu/IdeaProjects/myProjectOut/logs
    name: monitoringComputerLog.log

